[package]
name = "hmda_cli"
version = "0.1.0"
authors = ["Juan Marin Otero <juan.marin.otero@gmail.com>"]

[dependencies]
clap = "2.31.2"
prettytable-rs = "^0.6"
hmda = { git = "https://github.com/jmarin/hmda-lib" }
