[package]
name = "hmda"
version = "0.1.0"
authors = ["Juan Marin Otero <juan.marin.otero@gmail.com>"]

[dependencies]
clap = "2.31.2"
hyper = "0.11"
tokio-core = "0.1"
futures = "0.1"
hyper-tls = "0.1.3"
num_cpus = "1.0"
serde_json = "1.0"
