pub struct Loan {
    pub uli: String,
    pub application_date: String,
    pub loan_type: u8,
    pub loan_purpose: u8,
    pub construction_method: u8,
    pub occupancy: u8,
    pub amount: f64,
    pub loan_term: String,
    pub rate_spread: String,
    pub interest_rate: String,
    pub prepayment_penalty_term: String,
    pub debt_to_income_ratio: String,
    pub loan_to_value_ratio: String,
    pub introductory_rate_period: String,
}
