pub struct Loan {
    uli: String,
    application_date: String,
    loan_type: u8,
    loan_purpose: u8,
    construction_method: u8,
    occupancy: u8,
    amount: f64,
    loan_term: String,
    rate_spread: String,
    interest_rate: String,
    prepayment_penalty_term: String,
    debt_to_income_ratio: String,
    loan_to_value_ratio: String,
    introductory_rate_period: String,
}
